version: '3'

services:
  php:
    build: docker/php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/app
    environment:
      USE_XDEBUG: "yes"
      USE_OPCACHE: "yes"
      ENABLE_XDEBUG_FOR_MAC: "yes"
      WEBROOT: public

  database:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=secret
    volumes:
      - "db-data-sql:/var/lib/mysql"

volumes:
  db-data-sql: